language: python
services:
  - xvfb
addons:
  apt:
    packages:
      - chromium-browser
      - chromium-chromedriver
python:
  - 2.7
install:
  - pip install zc.buildout
  - buildout -c .travis.cfg
script:
  - bin/py.test
cache:
  pip: true
  directories:
    - eggs/
