language: python
services:
  - xvfb
addons:
  apt:
    packages:
      - firefox
      - firefox-geckodriver
python:
  - 2.7
install:
  - pip install zc.buildout
  - buildout -c .travis.cfg
script:
  - bin/test --all -vv --ndiff
