language: python
services:
  - xvfb
addons:
  apt:
    packages:
      - firefox
      - firefox-geckodriver
python:
  - 2.7
install:
  - python bootstrap.py -c .travis.cfg
  - bin/buildout -c .travis.cfg
script:
  - bin/test --all -vv --ndiff
