language: python
dist: bionic
services:
  - xvfb
addons:
  apt:
    packages:
      - chromium-browser
      - chromium-chromedriver
python:
  - 2.7
install:
  - pip install zc.buildout
  - buildout -c .travis.cfg
before_script:
  - chromium --version
  - chromedriver --version
  - chromedriver-update 80.0.3987.106
  - chromedriver --version
script:
  - bin/py.test
cache:
  pip: true
  directories:
    - eggs/
