language: python
python:
  - 2.6
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "export GOCEPT_SELENIUM_BROWSER='*firefox'"
install:
  - python bootstrap.py -c .travis.cfg
  - bin/buildout -c .travis.cfg
script:
  - bin/test --all -vv --ndiff