image: python:2.7.13

pipelines:
  default:
    - step:
        script:
          - python bootstrap.py -c bitbucket-pipelines.cfg
          - bin/buildout -n buildout:eggs-directory=../eggs -c bitbucket-pipelines.cfg
          - bin/py.test -k "not webdriver"
