image: python:2.7.13

pipelines:
  default:
    - step:
        script:
          - python bootstrap.py
          - bin/buildout -n buildout:eggs-directory=../eggs
          - bin/py.test -k "not webdriver"