image: python:2.7

pipelines:
  default:
    - step:
        caches:
          - pip
          - buildout-eggs
          - buildout-parts
        script:
          - apt-get -y remove liblzma-dev
          - pip install zc.buildout
          - buildout -n buildout:eggs-directory=../eggs -c bitbucket-pipelines.cfg
          - bin/py.test -k "not webdriver" --numprocesses=auto
definitions:
  caches:
    buildout-eggs: ../eggs
    buildout-parts: parts

