image: python:2.7.13

pipelines:
  default:
    - step:
        script:
          - pip install setuptools==35.0.2 zc.buildout
          - buildout -n buildout:eggs-directory=../eggs -c bitbucket-pipelines.cfg
          - bin/py.test -k "not webdriver"
